language: java

sudo: false

install: true

jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

addons:
 postgresql: "9.6"

postgres:
  adapter: postgresql
  database: lessons
  username: postgres

before_script:
  - "psql -c 'create database lessons;' -U postgres"

notifications:
  email:
    -llisovichok@gmail.com