language: java

services:
  -postgresql

addons:
 postgresql: "9.6"

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres

before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - "rake db:migrate"

notifications:
  email:
    -llisovichok@gmail.com